// <auto-generated />
namespace AppLockerLog.Data
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ApprovalAndUserGroups : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ApprovalAndUserGroups));
        
        string IMigrationMetadata.Id
        {
            get { return "201711281216237_ApprovalAndUserGroups"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
