// <auto-generated />
namespace AppLockerLog.Data
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddSoftwareEntry : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSoftwareEntry));
        
        string IMigrationMetadata.Id
        {
            get { return "201712080845532_AddSoftwareEntry"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
